// facts.js — a large pool of random facts for the "Learn something new"
// button (see fact-fx.js). Local and static on purpose: no external API,
// no key to configure, nothing that can fail or rate-limit. Add more
// entries any time — just keep each one a short, single-sentence string.
// (Backtick-delimited so apostrophes and quoted words inside facts don't
// need escaping.)

var FACTS = [
    `Honey never spoils — archaeologists have found 3,000-year-old honey in Egyptian tombs that is still edible.`,
    `Octopuses have three hearts and blue blood.`,
    `A day on Venus is longer than a year on Venus.`,
    `Bananas are berries, but strawberries are not.`,
    `The Eiffel Tower can be up to 15 cm taller in summer due to thermal expansion.`,
    `Wombat droppings are cube-shaped.`,
    `Sharks are older than trees.`,
    `A group of flamingos is called a "flamboyance."`,
    `Sea otters hold hands while sleeping so they do not drift apart.`,
    `The shortest war in recorded history lasted about 38 minutes (Britain vs. Zanzibar, 1896).`,
    `Hot water can freeze faster than cold water under certain conditions — a phenomenon known as the Mpemba effect.`,
    `Venus is the only planet in our solar system that rotates clockwise.`,
    `An octopus can change both the color and the texture of its skin in under a second.`,
    `Some cats are allergic to humans, developing skin irritation from human dander and skin cells.`,
    `The Great Barrier Reef is the largest living structure on Earth, visible from space.`,
    `A single cloud can weigh more than a million pounds.`,
    `Wi-Fi signals can be disrupted by bananas because of the water they contain.`,
    `The human nose can distinguish between one trillion different scents.`,
    `Bubble wrap was originally invented as a textured wallpaper in 1957.`,
    `There are more possible iterations of a chess game than atoms in the observable universe.`,
    `A bolt of lightning is roughly five times hotter than the surface of the sun.`,
    `The dot over a lowercase "i" or "j" is called a tittle.`,
    `Butterflies taste with their feet.`,
    `Some turtles can breathe through their butts (technically, through their cloaca).`,
    `A "jiffy" is an actual unit of time: 1/100th of a second.`,
    `The longest recorded flight of a chicken is 13 seconds.`,
    `Cows have best friends and can become stressed when separated from them.`,
    `It is impossible to hum while holding your nose closed.`,
    `Scotland has dozens of words for snow, including "snaw," "flinders," and "skelf."`,
    `Wearing headphones for just an hour can increase the bacteria in your ear by 700 times.`,
    `The unicorn is the national animal of Scotland.`,
    `The Mona Lisa has no eyebrows — it was fashionable in Renaissance Florence to shave them off.`,
    `A group of crows is called a "murder."`,
    `An adult human body contains around 37.2 trillion cells.`,
    `Sloths can hold their breath longer than dolphins can — up to 40 minutes.`,
    `The world's oldest known living tree is over 4,850 years old, a bristlecone pine in California.`,
    `Polar bears have black skin under their white fur.`,
    `The first oranges were not orange — the original oranges from Southeast Asia were green.`,
    `A snail can sleep for up to three years.`,
    `The Eiffel Tower has its own postal address and has received fan mail addressed to it.`,
    `Almonds are members of the peach family.`,
    `The total weight of ants on Earth is roughly comparable to the total weight of humans.`,
    `A group of pandas is called an "embarrassment."`,
    `Human tooth enamel is almost as hard as shark enamel.`,
    `The shortest commercial flight in the world lasts under two minutes, connecting two Scottish islands.`,
    `The Hawaiian alphabet has only 13 letters.`,
    `A rhinoceros horn is made of keratin, the same protein found in human hair and nails.`,
    `The inventor of the Pringles can, Fredric Baur, had his ashes buried in one.`,
    `Elephants are one of the few animals that can recognize themselves in a mirror.`,
    `Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.`,
    `Oxford University is older than the Aztec Empire.`,
    `A shrimp's heart is located in its head.`,
    `Some species of jellyfish are biologically immortal.`,
    `The average person walks the equivalent of roughly five times around the world in their lifetime.`,
    `Koala fingerprints are so similar to human fingerprints that they have occasionally confused crime scene investigators.`,
    `The word "set" has more definitions in the English language than any other word.`,
    `Starfish do not have brains or blood.`,
    `A day on Mercury lasts longer than its year — one Mercury day equals about 176 Earth days.`,
    `The longest common word in English without a vowel is "rhythms."`,
    `Honeybees can recognize individual human faces.`,
    `Ray Tomlinson chose the "@" symbol for email addresses simply because it was rarely used elsewhere.`,
    `Peanuts are not nuts — they are legumes, related to beans and lentils.`,
    `Some species of bamboo can grow up to 91 centimeters (35 inches) in a single day.`,
    `A crocodile cannot stick its tongue out.`,
    `The Great Wall of China is not actually visible from space with the naked eye.`,
    `Wombats are among the few animals known to produce cube-shaped feces.`,
    `The human heart creates enough pressure to squirt blood up to 30 feet.`,
    `Cows produce more milk when they listen to slow, calming music.`,
    `An ostrich's eye is bigger than its brain.`,
    `The first computer "bug" was an actual moth found trapped in a Harvard Mark II relay in 1947.`,
    `It rains diamonds on Jupiter and Saturn, according to atmospheric models.`,
    `The blob of toothpaste on a toothbrush is called a "nurdle."`,
    `The dwarf planet Pluto has a heart-shaped glacier on its surface named Tombaugh Regio.`,
    `A group of owls is called a "parliament."`,
    `Bananas are naturally slightly radioactive because of their potassium content.`,
    `Armadillos almost always give birth to identical quadruplets.`,
    `Percy Spencer invented the microwave oven after noticing a chocolate bar melted in his pocket near a radar tube.`,
    `The world's smallest known chameleon can fit on the tip of a matchstick.`,
    `A "moment" was a medieval unit of time equal to about 90 seconds.`,
    `Kangaroos cannot walk backwards.`,
    `The Sahara Desert was a lush green landscape with lakes and rivers as recently as about 10,000 years ago.`,
    `Human blood is never actually blue — it only looks that way through skin; it turns bright red the moment it meets oxygen.`,
    `A group of camels is called a "caravan" or a "train."`,
    `The longest recorded throw-and-catch distance for a boomerang by its original thrower is over 238 meters.`,
    `The tallest mountain in the solar system is Olympus Mons on Mars, about three times the height of Mount Everest.`,
    `Some species of clams can live for more than 500 years.`,
    `The heart of a blue whale is roughly the size of a small car.`,
    `Chess was banned in Iran for a period during the 1980s over religious concerns about gambling.`,
    `The dot on a lowercase "i" comes from an old Latin scribal practice meant to separate letters that looked identical.`,
    `Slugs have four noses.`,
    `A single strand of spaghetti is called a "spaghetto."`,
    `The famous unicorn tapestries at The Met are among the most celebrated surviving medieval artworks.`,
    `Human beings share a surprisingly large fraction of their DNA with a banana.`,
    `The world's largest desert is actually Antarctica, not the Sahara.`,
    `A crocodile's bite force is one of the strongest of any living animal, but the muscles that open its mouth are surprisingly weak.`,
    `The first alarm clock invented in the U.S. could only ring at 4 a.m.`,
    `Cats spend about 70% of their lives asleep.`,
    `The Amazon rainforest produces a substantial share of the world's oxygen.`,
    `A golden eagle can kill a young deer and fly away carrying it.`,
    `The word "nerd" first appeared in a Dr. Seuss book, "If I Ran the Zoo," in 1950.`,
    `Venus has a surface hot enough to melt lead, largely due to a runaway greenhouse effect.`,
    `A group of jellyfish is called a "smack."`,
    `The longest engagement on record lasted 67 years, between a couple in Mexico.`,
    `The average cumulus cloud weighs about 1.1 million pounds.`,
    `Some species of mushrooms can glow in the dark through a process called bioluminescence.`,
    `Dolphins have names for each other in the form of unique signature whistles.`,
    `Twitter's bird logo has a name: Larry.`,
    `A hummingbird's heart can beat up to 1,260 times per minute during flight.`,
    `In the world's quietest room — an anechoic chamber — people report being able to hear their own blood flow.`,
    `Table tennis was originally called "whiff-whaff."`,
    `The Ferris wheel was invented to try to out-do the Eiffel Tower at the 1893 World's Fair.`,
    `Astronauts describe the smell of space, lingering on their suits after a spacewalk, as similar to burnt steak or hot metal.`,
    `A group of rhinos is called a "crash."`,
    `Antarctica is the largest desert on Earth, a classification based on low precipitation rather than heat.`,
    `Octopuses have nine brains — one central brain and one in each of their eight arms.`,
    `The first item ever sold on eBay was a broken laser pointer.`,
    `Rats emit ultrasonic chirps resembling laughter when they are tickled.`,
    `A day on Earth is very slowly getting longer, by about 1.7 milliseconds per century, due to tidal friction from the Moon.`,
    `The longest word that can be typed using only the top row of a QWERTY keyboard is "typewriter."`,
    `Termite mounds can include built-in ventilation systems that regulate internal temperature.`,
    `A shrimp's brain is located near its throat, while its heart is in its head.`,
    `The world's first webcam was built at Cambridge University to monitor the level of a coffee pot.`,
    `A sneeze can send droplets out of your mouth at speeds up to 100 miles per hour.`,
    `Owls cannot move their eyes in their sockets, so they rotate their heads up to 270 degrees instead.`,
    `The longest possible total solar eclipse is about 7.5 minutes.`,
    `Some species of frogs can be frozen solid during winter and thaw out alive in spring.`,
    `The average person spends several months of their life waiting for red lights to turn green.`,
    `A rainbow can only be seen if the sun is behind the observer and rain is in front.`,
    `Giraffes have the same number of neck vertebrae as humans — seven.`,
    `The first product ever scanned with a barcode at a retail checkout was a pack of chewing gum, in 1974.`,
    `Arthur Wynne published the first modern crossword puzzle in a New York newspaper in 1913.`,
    `Some spiders "balloon" through the air on threads of silk carried by the wind, traveling for miles.`,
    `The Pacific Ocean is so large it contains more than half of the free water on Earth.`,
    `A hedgehog's heart beats around 300 times per minute.`,
    `It takes sunlight about 8 minutes and 20 seconds to travel from the Sun to Earth.`,
    `The Statue of Liberty's copper exterior is only about as thick as two stacked pennies.`,
    `A group of ferrets is called a "business."`,
    `One of the largest snowflakes on record was reportedly 15 inches wide, recorded in Montana in 1887.`,
    `Cats have a special organ called the Jacobson's organ that lets them "taste" scents in the air.`,
    `A recorded sneezing fit once lasted 978 days.`,
    `The blue whale is the largest animal known to have ever existed, larger than any dinosaur.`,
    `A "murmuration" is the name for the swirling flight pattern of a large flock of starlings.`,
    `Ancient Greek water clocks used whistles or bells to mark time for study and civic life.`,
    `A group of hedgehogs is called an "array."`,
    `Some house cats have lived past the age of 30.`,
    `Some species of ants can carry objects up to 50 times their own body weight.`,
    `The Moon has moonquakes, caused by gravitational tidal stress from the Earth.`,
    `"Petrichor" is the scientific name for the smell of rain hitting dry earth.`,
    `Ancient Egypt is credited with some of the earliest known coin-operated dispensers, used for holy water.`,
    `Snails have thousands of tiny teeth arranged on a ribbon-like tongue called a radula.`,
    `A group of frogs is called an "army."`,
    `The Sun accounts for about 99.86% of all the mass in the solar system.`,
    `Woodpeckers have shock-absorbing structures in their skulls that help prevent brain injury while pecking.`,
    `The Great Barrier Reef is made up of over 2,900 individual reefs.`,
    `A group of porcupines is called a "prickle."`,
    `The dwarf planet Ceres, located in the asteroid belt, contains almost a third of the belt's total mass.`,
    `Some species of turtles can live over 150 years.`,
    `The earliest known print use of "OK" dates to a Boston newspaper in 1839, as a joking abbreviation.`,
    `A group of squirrels is called a "scurry."`,
    `Some species of shrimp can produce a claw "snap" so fast it creates a shockwave that stuns prey.`,
    `The word "trivia" comes from the Latin for "three roads," a place where paths crossed and people gathered to chat.`,
    `The Great Basin bristlecone pine can survive for millennia in extremely harsh, dry, high-altitude conditions.`,
    `A group of butterflies is called a "kaleidoscope."`,
    `The dwarf planet Eris is more massive than Pluto, and its discovery contributed to Pluto's reclassification in 2006.`,
    `Some species of geckos can detach their tails to escape predators, then slowly regrow them.`,
    `A group of hippos is called a "bloat."`,
    `The Mariana Trench is so deep that Mount Everest could sit inside it with its peak still over a mile underwater.`,
    `Some plants, like the Venus flytrap, can effectively "count" — their traps only close after being touched twice within about 20 seconds.`,
    `A group of toads is called a "knot."`,
    `Veryovkina Cave in Georgia (the country) plunges more than 2,200 meters underground, among the deepest known caves.`,
    `A group of larks is called an "exaltation."`,
    `Gideon Sundback patented the modern zipper design in 1917 after earlier "clasp locker" attempts had failed.`,
    `Some species of eels can generate electric discharges of several hundred volts.`,
    `A group of jellyfish, in very large numbers, is sometimes called a "bloom."`,
    `"Quarantine" comes from the Italian "quaranta giorni," meaning "forty days," referring to historic ship isolation periods.`,
    `Mantis shrimp can perceive a far wider range of colors than humans, with many more types of color receptors.`,
    `A group of storks is called a "muster."`,
    `The dwarf planet Makemake was named after a creation deity from Rapa Nui (Easter Island) mythology.`,
    `Some species of ants practice a form of agriculture, farming fungus for food inside their colonies.`,
    `A group of woodpeckers is called a "descent."`,
    `László Bíró, inventor of the modern ballpoint pen, reportedly got the idea from watching newspaper ink dry quickly.`,
    `An octopus can squeeze through any gap larger than its beak, the only hard part of its body.`,
    `A group of hawks is called a "kettle" when seen circling on a rising thermal.`,
    `London's first traffic light, installed in 1868, used gas lamps and later exploded, injuring a police officer.`,
    `Some species of bats can live over 30 years despite their small size.`,
    `A group of geese on the ground is called a "gaggle," but in flight it is called a "skein."`,
    `The dwarf planet Haumea is shaped like an elongated egg due to its extremely fast rotation.`,
    `Tardigrades ("water bears") can survive being frozen, dried out, and even briefly exposed to the vacuum of space.`,
    `One especially long-lasting rainbow was observed for almost nine hours over Yorkshire, England, in 2017.`,
    `A group of lions is called a "pride," while a group of leopards is called a "leap."`,
    `George de Mestral invented Velcro after finding burrs stuck to his dog's fur and examining them under a microscope.`,
    `The snap of a pistol shrimp's claw can briefly produce temperatures approaching that of the sun's surface, at a tiny scale.`,
    `A group of bats is called a "colony" when roosting and a "cloud" when in flight.`,
    `The Antikythera mechanism, an ancient Greek device over 2,000 years old, could predict astronomical positions and eclipses.`,
    `A group of crows gathering around a dead crow is sometimes described, informally, as holding a "funeral."`,
    `The Library of Alexandria was one of the largest and most significant libraries of the ancient world before its decline.`,
    `A group of parrots is called a "pandemonium."`,
    `Vantablack, one of the darkest substances ever created, absorbs more than 99% of visible light.`,
    `A group of whales is called a "pod" or, less commonly, a "gam."`,
    `The inventor of the modern lightbulb, Thomas Edison, held over a thousand US patents in his lifetime.`,
    `A group of foxes is called a "skulk" or a "leash."`,
    `Chameleons' eyes can move independently of each other, letting them look in two directions at once.`,
    `A group of ravens is called an "unkindness."`,
    `Honey badgers are known for being remarkably fearless, sometimes confronting animals many times their size.`,
    `A group of giraffes is called a "tower."`,
    `The blue-ringed octopus, despite being tiny, carries enough venom to be lethal to an adult human.`,
    `A group of zebras is called a "dazzle."`,
    `Mount Everest grows a few millimeters taller each year due to ongoing tectonic plate movement.`,
    `A group of kangaroos is called a "mob."`,
    `Some species of cicadas spend over a decade underground as nymphs before emerging as adults for just a few weeks.`,
    `A group of otters is called a "romp."`,
    `The coldest temperature ever recorded on Earth's surface was in Antarctica, well below -89°C (-128°F).`,
    `A group of peacocks is called a "muster" or an "ostentation."`,
    `Wind turbines can be found generating power even in some of the most remote deserts on Earth.`,
    `A group of turtles is called a "bale."`,
    `The Andes is the longest continental mountain range in the world, stretching across seven countries.`,
    `A group of walruses is called a "huddle" or a "pod."`,
    `Some deep-sea anglerfish attract prey using a glowing lure formed from a modified fin spine.`,
    `A group of skunks is called a "surfeit."`,
    `The tallest known living tree, a coast redwood, stands taller than a 30-story building.`,
    `A group of badgers is called a "cete."`,
    `Some migratory birds can fly thousands of miles nonstop, relying on fat reserves for fuel.`,
    `A group of moles is called a "labour."`,
    `The Danakil Depression in Ethiopia is one of the hottest and most inhospitable inhabited places on Earth.`,
    `A group of weasels is called a "confusion" or a "boogle."`,
    `Some species of coral can live for thousands of years, growing new layers very slowly over time.`,
    `A group of bears is called a "sloth" or a "sleuth."`,
    `The world's largest living organism by area is a giant fungus network in Oregon, spanning several square miles underground.`,
    `A group of wolves is called a "pack" or, in older usage, a "route."`,
    `The Dead Sea is so dense with salt that swimmers float almost effortlessly on its surface.`,
    `A group of buffalo is called an "obstinacy."`,
    `Some spiders can survive underwater for extended periods by trapping air bubbles in fine body hairs.`,
    `A group of rabbits is called a "fluffle" in casual usage, or more formally a "colony."`,
    `The Northern Lights, or aurora borealis, are caused by charged particles from the sun colliding with Earth's atmosphere.`,
    `A group of cheetahs is called a "coalition," typically referring to males that live and hunt together.`,
    `Iceland has no native mosquitoes, one of the very few places in the world where this is true.`,
    `A group of elk is called a "gang" or a "herd."`,
];
